### ISSUE TITLE
Swagger tests don't use tiny types

### ISSUE THREAD

**Issue by Octember** [paradoxical-io/finatra-extensions#1]
Tiny types demo uses `HttpServiceBase`, which brings in `SwaggerDocs`

https://github.com/paradoxical-io/finatra-extensions/blob/master/finatra-server/src/test/scala/io/paradoxical/finatra/sample/SampleServer.scala#L12

This works fine, but the swagger docs extend `HttpServer` directly, not bringing in `SwaggerDocs`

It's unclear whether bringing in `SwaggerDocs` messes with the swagger implementation therein... I have to dig a bit deeper

But it would be rad to have a test demoing the usage of both!

**Comment by Octember** [comment]
OK Yeah, they're somewhat incopatible. Things work fine in either path but to get both working I had to do 

```
object App extends HttpServer {
  override protected def jacksonModule: Module = new JsonModule()
```
![](https://fulldegreeheyyouau.files.wordpress.com/2017/10/why-not-both-animated-gif-7.gif?w=748)

**Comment by devshorts** [comment]
Fixed
